name: Tweet Message Action
author: lazy-actions
description: Tweet message to twitter
inputs:
  message:
    description: Plain message to tweet
    required: false
  data:
    description: Parameters to render in template
    required: false
  data_filename:
    description: Filename where data is saved
    required: false
  template:
    description: Template string based on EJS
    required: false
  template_filename:
    description: Filename where template is written
    required: false
  oauth_consumer_key:
    description: API key for OAuth 1.0a
    required: true
  oauth_consumer_secret:
    description: API secret for OAuth 1.0a
    required: true
  oauth_token:
    description: Access token for OAuth 1.0a
    required: true
  oauth_token_secret:
    description: Access token secret for OAuth 1.0a
    required: true
runs:
  using: node12
  main: dist/index.js
branding:
  icon: hash
  color: blue